version: '3'
services:
    nginx:
        image: nginx:1.10
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: ./docker
            dockerfile: php.docker
        volumes:
            - ./:/var/www
        depends_on:
            - db
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./docker/storage/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
            - "MYSQL_DATABASE=test"
    adminer:
        image: adminer
        restart: always
        ports:
            - 8094:8080
